userfront/guide

docs/.vuepress/config.js, docs/guide/cohort-analysis.md, docs/guide/cohort.md, docs/guide/create-cohort-analysis.md, docs/guide/index.md
=> Add articles on cohort analysis

docs/.vuepress/config.js, docs/guide/auth-landscape.md, docs/guide/authentication.md, docs/guide/cohort-analysis.md, docs/guide/cohort.md, docs/guide/login.md, docs/guide/logout.md, docs/guide/reset.md, docs/guide/signup.md
=> Add authentication article

docs/.vuepress/config.js, docs/guide/auth-landscape.md, docs/guide/auth-token-types.md, docs/guide/jwt.md
=> 7 auth landscape

docs/.vuepress/config.js, docs/guide/import-export.md
=> Add instructions for import export

docs/.vuepress/config.js, docs/auth.md, docs/dev-mode.md, docs/quickstart.md
=> 16 auth setup

docs/.vuepress/enhanceApp.js, docs/quickstart.md, docs/scratch.md
=> 21 quickstart mod

.prettierrc.yml
=> Added prettier file with defaults

guide/.vuepress/config.js, guide/.vuepress/public/_redirects, guide/examples/react.md
Closes https://github.com/anymod/marketing/issues/28
=> Update react example

guide/.vuepress/config.js, guide/glossary.md
=> Add glossary

all/.vuepress/config.js, all/.vuepress/styles/palette.styl, all/examples/index.md, all/guide/index.md
=> Use custom sidebars

all/.vuepress/enhanceApp.js, package.json
=> Redirect to /guide/

all/tutorials/react-authentication.md, all/vs/best-auth-comparison-auth0-okta-firebase-cognito.md
=> Add react tutorial

all/.vuepress/components/code-samples.vue, all/.vuepress/enhanceApp.js, all/.vuepress/plugins/codeCopy/clientRootMixin.js
=> Use fresh code for copies

all/guide/test-mode.md
=> Update test mode page

all/guide/import-export.md, all/guide/toolkit/login.md, all/guide/toolkit/logout.md, all/guide/toolkit/reset.md, all/guide/toolkit/signup.md
=> Add redirect and email docs

all/.vuepress/components/iframe-demo.vue, all/guide/glossary.md, all/guide/toolkit/automatic-login-form-html.md, all/guide/toolkit/automatic-logout-button-html.md, all/guide/toolkit/automatic-password-reset-form-html.md, all/guide/toolkit/automatic-signup-form-html.md
=> Finish auto docs

all/.vuepress/components/install-html.vue, all/.vuepress/components/install-react.vue, all/.vuepress/components/tenant-picker.vue, all/.vuepress/components/toolkit-breadcrumb.vue, all/.vuepress/components/toolkit-initial-picker.vue, all/.vuepress/constants.js, all/.vuepress/enhanceApp.js, all/.vuepress/public/_redirects, all/.vuepress/theme/styles/code.styl, all/guide/glossary.md, all/guide/toolkit/automatic-login-form-react.md, all/guide/toolkit/automatic-logout-button-react.md, all/guide/toolkit/automatic-password-reset-form-react.md, all/guide/toolkit/automatic-signup-form-react.md, all/guide/toolkit/build-login-form-html.md, all/guide/toolkit/build-login-form-react.md, all/guide/toolkit/build-logout-button-html.md, all/guide/toolkit/build-logout-button-react.md, all/guide/toolkit/build-password-reset-form-react.md, all/guide/toolkit/build-signup-form-html.md, all/guide/toolkit/build-signup-form-react.md, all/guide/toolkit/index.md, all/guide/toolkit/login.md, all/guide/toolkit/logout.md, all/guide/toolkit/signup.md
=> 78 react forms

all/.vuepress/config.js, all/.vuepress/styles/palette.styl, all/examples/index.md, all/examples/react.md, all/examples/vue.md
=> 88 vue example

all/.vuepress/components/toolkit-initial-picker.vue, all/.vuepress/config.js, all/.vuepress/enhanceApp.js, all/guide/sso/index.md, all/guide/toolkit/index.md
=> Adding SSO guide

all/.vuepress/components/code-samples.vue
=> Update nodejs examples

all/docs/js.md
=> Add user examples and move to 2 columns

all/.vuepress/utils/store.js
=> Fix bug in setInstallation

all/.vuepress/config.js, all/guide/auth/index.md, all/guide/auth/jwt-json-web-token.md, all/guide/auth/jwt-public-private-keys.md, all/guide/auth/multi-tenancy.md
=> 89 refresh token

all/guide/test-mode.md
=> Add note about live mode origin

all/guide/toolkit/build-signup-form-react.md, all/guide/toolkit/build-signup-form-vue.md
=> 141 sso documentation

all/.vuepress/components/code-samples-client.vue, all/docs/api-client.md
=> Add documentation for refresh endpoint

all/.vuepress/components/access-level.vue, all/.vuepress/components/code-samples-client.vue, all/.vuepress/components/code-samples.vue, all/docs/api-client.md, all/docs/api.md
=> 147 api keys

all/.vuepress/utils/store.js, all/examples/react.md, all/examples/vue.md, all/guide/toolkit/build-logout-button-html.md, all/guide/toolkit/build-logout-button-react.md, all/guide/toolkit/build-logout-button-vue.md, all/tutorials/react-authentication.md
=> Use new accessToken reference

all/docs/api.md
=> Add docs for invite routes

all/docs/api.md
=> Add docs for options.duration and options.reset

all/docs/api.md
=> Document the link options

all/docs/api.md
Glance
Closes #184 
Adds `tenant.data` to "Create tenant" and "Update tenant" endpoints.
=> Add tenant.data

all/docs/api-client.md, all/docs/js.md
=> Add sendSms & login 'mfa'

all/guide/passthrough.md
=> 186 passthrough

all/docs/api-client.md
Glance
Closes #189 
Add documentation for `options.noResetEmail`
=> Add docs for noResetEmail

all/docs/api-client.md, all/docs/js.md
Glance
Closes #196  
I did a find/replace for all permutations of "security code" and replaced with the equivalent "verification code".
=> Rename security code to verification code

all/docs/api-client.md, all/docs/js.md, all/guide/sso/index.md
=> Add apple notes

all/docs/api-client.md
Glance
Closes #202 
Updates docs for new error response.
=> Document error responses

all/docs/js.md
Glance
Closes #214 
Adds documentation for the `updatePassword` method.
=> Add updatePassword info to sendResetLink
